initialBackgroundImage: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493658866-h0aa7.png
backgroundImages:
  main:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493658866-h0aa7.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493658866-h0aa7.png
  pebble:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131687-uk0fw.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131286-3doz7.png
  napa:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131630-x3o5f.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131255-om2c5.png
  choose_car:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132235-deeow.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132235-deeow.png
  crack:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131700-kcw6f.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131311-44pyu.png
  door:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131721-6oh8e.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131321-t0wy6.png
  stadium:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131853-933cw.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131334-yb3z2.png
  cleanup:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/undefined
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131506-8x3wi.png
  home:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493658866-h0aa7.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493658866-h0aa7.png
  burger:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493468347-w6on4.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131389-glx4i.png
  lunch_sf:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132033-x6adq.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131371-4xqnx.png
  gym:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131678-hbo3m.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131678-hbo3m.png
  chris_arrives:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132272-3od7p.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131547-h3t5b.png
  day_off:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131662-kd86t.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131274-tivh7.png
  chris_start:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132286-2r7cb.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131508-czl9h.png
  vomit:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131615-nl3pv.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131245-2ktx5.png
  caltrain:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132226-7g9g1.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131590-wnrrj.png
  nice:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131874-j6agc.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131358-ldzmh.png
  normal_start:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493658866-h0aa7.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493658866-h0aa7.png
  night_sac:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131836-kbref.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131836-kbref.png
  driving:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132080-rceaa.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131410-34i2r.png
  son:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132007-0g3if.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131401-0rpyi.png
  end_day:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132115-eyqaw.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131447-5nr5r.png
  driving_sf:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132103-q12u8.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132103-q12u8.png
  lunch_sac:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131993-74ila.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131423-l60o6.png
  airport:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131645-lusmj.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493131645-lusmj.png
  driving_sac:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132193-1tg67.png
    minvan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8493132193-1tg67.png
