initialBackgroundImage: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953249-55mpn.png

backgroundImages:
  airport:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953034-26ze6.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952384-4l0e5.png
  burger:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953330-95nj6.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952564-dntpi.png
  caltrain:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953722-7xles.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952729-tudty.png
  choose_car:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953707-3vl4h.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953707-3vl4h.png
  chris_arrives:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953696-tujia.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952715-x1z98.png
  chris_start:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953686-07o0v.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952703-20wkm.png
  cleanup:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953677-p4l6o.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952694-r9chq.png
  crack:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953074-fuysu.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952494-awhx7.png
  day_off:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953043-sd213.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952404-8hxmg.png
  door:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953130-9u1lu.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952505-18kvo.png
  driving:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953602-vqiia.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952607-1rggc.png
  driving_sac:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953668-mq5un.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953668-mq5un.png
  driving_sf:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953620-gut3k.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953620-gut3k.png
  home:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953643-afl3i.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952682-li1ve.png
  gym:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953054-zrqbt.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953054-zrqbt.png
  night:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953593-zciyy.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953593-zciyy.png
  lunch_sac:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492951897-54gk0.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492951856-2n2gs.png
  lunch_sf:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953318-5kyk3.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952550-cig6f.png
  main:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953249-55mpn.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953249-55mpn.png
  napa:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952800-12si0.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952369-mrt6u.png
  nice:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953293-sqs5k.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952538-ey3yk.png
  night_sac:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953259-4jjck.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953259-4jjck.png
  night_sf:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953632-6c93i.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952596-nv0ws.png
  pebble:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953063-81gz6.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952425-spk12.png
  son:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953399-wbm1q.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952581-rxmc3.png
  stadium:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492953282-rdwvj.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952523-p1w53.png
  vomit:
    prius: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952790-iovbq.png
    minivan: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492952358-8qc2d.png

endingImages:
  happy: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492959674-3xf4r.png
  sad: http://ft-ig-images-prod.s3-website-eu-west-1.amazonaws.com/v1/8492880811-t8unk.png
