# This config is for a large set of stylistic rules useful for lint highlighting.
# This ruleset is not used in CI as it would be too strict.

root: true
extends:
  - airbnb
  - plugin:flowtype/recommended
parser: babel-eslint
env:
  browser: true
plugins:
  - babel
  - flowtype
rules:
  react/react-in-jsx-scope: off
  react/jsx-filename-extension: off
  function-paren-newline: off # HACK because of incompatibility with Prettier
  import/no-extraneous-dependencies: [2, {}]
